### ISSUE TITLE
Model Checkpoint of Panoptic Seg

### ISSUE THREAD

**Issue by ashun989** [jiaosiyu1999/MAFT-Plus#2]
Thank you for your nice work. When can you release the checkpoint training on the coco-pan?

**Comment by jiaosiyu1999** [comment]
Hi, the [checkpoint](https://drive.google.com/file/d/1znk_uco8fwvbA0kndy4kGyVp22KbQr6g/view?usp=drive_link) for training on the COCO-Pan has been updated.
